boot.o: boot.S multiboot.h x86_desc.h types.h
page_asm.o: page_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h page.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
